const subject=[
    { "test": "test1", "subject": "biology" },
    { "test": "test2", "subject": "biology" },
    { "test": "test3", "subject": "biology" },
    { "test": "test4", "subject": "biology" },
    { "test": "test5", "subject": "biology" },
    { "test": "test6", "subject": "biology" },
    { "test": "test7", "subject": "biology" },
    { "test": "test8", "subject": "biology" },
    { "test": "test9", "subject": "biology" },
    { "test": "test10", "subject": "biology" },
    { "test": "test11", "subject": "biology" },
    { "test": "test12", "subject": "biology" },
    { "test": "test13", "subject": "biology" },
    { "test": "test14", "subject": "biology" },
    { "test": "test15", "subject": "biology" },
    { "test": "test16", "subject": "biology" },
    { "test": "test17", "subject": "biology" },
    { "test": "test18", "subject": "biology" },
    { "test": "test19", "subject": "biology" },
    { "test": "test20", "subject": "biology" },
    { "test": "test21", "subject": "biology" },
    { "test": "test22", "subject": "biology" },
    { "test": "test23", "subject": "biology" },
    { "test": "test24", "subject": "biology" },
    { "test": "test25", "subject": "biology" },
    { "test": "test26", "subject": "biology" },
    { "test": "test27", "subject": "biology" },
    { "test": "test28", "subject": "biology" },
    { "test": "test29", "subject": "biology" },
    { "test": "test30", "subject": "biology" }
]

export default subject